### ISSUE TITLE
Why not use `CSSRule.cssText`

### ISSUE THREAD

**Issue by mantou132** [tomhodgins/stringify-css-stylesheet#1]
https://github.com/tomhodgins/stringify-css-stylesheet/blob/master/index.js#L6
https://developer.mozilla.org/en-US/docs/Web/API/CSSRule/cssText

**Comment by tomhodgins** [comment]
Hi @mantou132 in the end it does, here's how it's stringifies:

```js
function(rule) {
  return rule.cssText || ''
}
```

If you're looking at this lib you might be interested in the more complete and integrated [cssomtools](https://github.com/tomhodgins/cssomtools)!
